# Generated by Django 6.0 on 2025-12-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_generator', '0004_ensure_accounts_tests_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
