# Generated by Django 6.0 on 2025-12-07 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_generator', '0005_alter_testentry_id'),
        ('test_generator', '0005_testentry_owner'),
    ]

    operations = [
    ]
