# Generated by Django 5.1.15 on 2026-01-11 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_grader', '0003_alter_submission_id_alter_test_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='allow_multiple_submissions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='is_open_for_submissions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='share_code',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(condition=models.Q(('student_user__isnull', False)), fields=('test', 'student_user'), name='unique_student_submission'),
        ),
    ]
